config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi|ja/ do
    mount Ckeditor::Engine => '/ckeditor'
    root "static_pages#home"
    get  '/breast_cancer', to: "static_pages#breast_cancer"
    get  '/data_mining', to: "static_pages#data_mining"
    get  '/data_set', to: "static_pages#data_set"
    devise_for :users

    resources :users
    resources :diagnoses
    resources :groups do
      member do
        post :delete_member
      end
      member do
        post :add_member
      end
    end
    resources :test_algorithms
    resources :user_groups
    resources :fictions
    resources :abouts
    namespace :admin do
      root "users#index"
      resources :data_cancers
      resources :users
      resources :fictions
      resources :value_fictions
      resources :test_algorithms
      resources :diagnoses
      resources :groups
      resources :user_groups
      resources :rules
      resources :rule_id3s
      resources :abouts
      resources :knowledges do
        collection do
          get :create_knowledge
        end
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :load_breast_cancer, only: :breast_cancer
  before_action :load_data_mining, only: :data_mining
  before_action :load_data_set, only: :data_set

  def home
  end

  def breast_cancer
    @title = t "home_infor.infor_breast_cancer"
  end

  def data_mining
    @title = t "home_infor.infor_data_mining"
  end

  def data_set
    @title = t "home_infor.infor_data_set"
  end

  private

  def load_breast_cancer
    about_breast_cancers = About.load_by_type(:breast_cancer)
    @about = about_breast_cancers.last if about_breast_cancers.present?
    @fictions = Fiction.all
    return if @about.present?
    flash[:error] = t "not_found_item"
    redirect_to root_path
  end

  def load_data_mining
    about_data_minings = About.load_by_type(:data_mining)
    @about = about_data_minings.last if about_data_minings.present?
    return if @about.present?
    flash[:error] = t "not_found_item"
    redirect_to root_path
  end

  def load_data_set
    about_data_sets = About.load_by_type(:data_set)
    @about = about_data_sets.last if about_data_sets.present?
    return if @about.present?
    flash[:error] = t "not_found_item"
    redirect_to root_path
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/breast_cancer.html.erb
<section class="site-content site-section">
    <div class="container">
        <!-- Project Navigation -->
        <div class="site-block clearfix">
            <div class="btn-group pull-right">
                <%= link_to data_set_path, class: "btn btn-primary" do %>
                    <i class="fa fa-chevron-left"></i> Prev
                <% end %>
                 <%= link_to data_mining_path, class: "btn btn-primary" do %>
                    <i class="fa fa-chevron-right"></i> Next
                <% end %>
            </div>
            <%= link_to root_path, class: "btn btn-primary pull-left"  do %>
                <i class="fa fa-th-large"></i>
                <%= t("home")%>
            <% end %>
        </div>
        <!-- END Project Navigation -->
        <!-- Project Info -->
        <div class="row">
            <!-- Project Slider -->
            <div class="col-sm-5 site-block">
                <div id="project-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner text-center">
                        <div class="active item">
                            <%= image_tag "home/b1.jpg" %>
                        </div>
                        <div class="item">
                            <%= image_tag "home/b2.jpg" %>
                        </div>
                        <div class="item">
                            <%= image_tag "home/b3.jpg" %>
                        </div>
                    </div>
                    <!-- END Wrapper for slides -->

                    <!-- Controls -->
                    <a class="left carousel-control" href="#project-carousel" data-slide="prev">
                        <span>
                            <i class="fa fa-chevron-left"></i>
                        </span>
                    </a>
                    <a class="right carousel-control" href="#project-carousel" data-slide="next">
                        <span>
                            <i class="fa fa-chevron-right"></i>
                        </span>
                    </a>
                    <!-- END Controls -->
                </div>

                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td style="width: 50%;"><strong><%= t "home_infor.source" %></strong></td>
                            <td class="text-right"><%= @about.source %></td>
                        </tr>
                        <tr>
                            <td><strong><%= t "home_infor.category" %></strong></td>
                            <td class="text-right"><%= t "home_infor.infor_breast_cancer" %></td>
                        </tr>
                        <tr>
                            <td><strong>Website</strong></td>
                            <td class="text-right"><a href="javascript:void(0)"><%= @about.link %></a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- END Project Slider -->

            <!-- Project Details -->
            <div class="col-sm-7 site-block">
                <h3 class="site-heading"><strong><%= t("home_infor.quest_first") %></strong><%= t("home_infor.breast_cancer") %></h3>
                   <% if is_locale_en? %>
                    <%= @about.description.html_safe  if @about.description.present? %>
                   <% else %>
                    <%= @about.description_vi.html_safe if @about.description_vi.present? %>
                   <% end %>
             </div>
            <!-- END Project Details -->
        </div>
        <!-- END Project Info -->
        <hr>
         <!-- Key Features -->
            <section class="site-content site-section">
                <div class="container">
                    <div class="row">
                        <% @fictions.each do |fiction| %>
                            <div class="col-sm-4 site-block">
                                <h3 class="site-heading"><i class="fa fa-check text-success animation-pulse"></i> <strong><%= fiction.name %></strong></h3>
                                <% if is_locale_en? %>
                                    <p class="remove-margin"><%= fiction.description.html_safe if fiction.description.present? %></p>
                                <% else %>
                                    <p class="remove-margin"><%= fiction.description_vi.html_safe if fiction.description_vi.present? %></p>
                                <% end %>
                            </div>
                        <% end %>
                    </div>
                    <hr>
                </div>
            </section>
            <!-- END Key Features -->
    </div>

</section>
<!-- END Content -->

app/views/static_pages/data_mining.html.erb
<section class="site-content site-section">
    <div class="container">
        <!-- Project Navigation -->
        <div class="site-block clearfix">
            <div class="btn-group pull-right">
                <%= link_to breast_cancer_path, class: "btn btn-primary" do %>
                    <i class="fa fa-chevron-left"></i> Prev
                <% end %>
                 <%= link_to data_set_path, class: "btn btn-primary" do %>
                    <i class="fa fa-chevron-right"></i> Next
                <% end %>
            </div>
            <%= link_to root_path, class: "btn btn-primary pull-left"  do %>
                <i class="fa fa-th-large"></i>
                <%= t("home")%>
            <% end %>
        </div>
        <!-- END Project Navigation -->

        <!-- Project Info -->
        <div class="row">
            <!-- Project Slider -->
            <div class="col-sm-5 site-block">
                <div id="project-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner text-center">
                        <div class="active item">
                            <%= image_tag "home/d1.jpg" %>
                        </div>
                        <div class="item">
                            <%= image_tag "home/d2.jpg" %>
                        </div>
                        <div class="item">
                            <%= image_tag "home/d3.jpg" %>
                        </div>
                    </div>
                    <!-- END Wrapper for slides -->

                    <!-- Controls -->
                    <a class="left carousel-control" href="#project-carousel" data-slide="prev">
                        <span>
                            <i class="fa fa-chevron-left"></i>
                        </span>
                    </a>
                    <a class="right carousel-control" href="#project-carousel" data-slide="next">
                        <span>
                            <i class="fa fa-chevron-right"></i>
                        </span>
                    </a>
                    <!-- END Controls -->
                </div>

                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td style="width: 50%;"><strong><%= t "home_infor.source" %></strong></td>
                            <td class="text-right"><%= @about.source %></td>
                        </tr>
                        <tr>
                            <td><strong>Category</strong><%= t "home_infor.infor_data_mining" %></td>
                            <td class="text-right">wikipedia</td>
                        </tr>
                        <tr>
                            <td><strong>Website</strong></td>
                            <td class="text-right"><a href="javascript:void(0)"><%= @about.link %></a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- END Project Slider -->

            <!-- Project Details -->
            <div class="col-sm-7 site-block">
                <h3 class="site-heading"><strong><%= t("home_infor.quest_first") %></strong><%= t("home_infor.data_mining") %></h3>
                   <% if is_locale_en? %>
                    <%= @about.description.html_safe  if @about.description.present? %>
                   <% else %>
                    <%= @about.description_vi.html_safe if @about.description_vi.present? %>
                   <% end %>
             </div>
            <!-- END Project Details -->
        </div>
        <!-- END Project Info -->
        <hr>
    </div>
</section>
<!-- END Content -->

app/views/static_pages/data_set.html.erb
<section class="site-content site-section">
    <div class="container">
        <!-- Project Navigation -->
        <div class="site-block clearfix">
            <div class="btn-group pull-right">
                <%= link_to data_mining_path, class: "btn btn-primary" do %>
                    <i class="fa fa-chevron-left"></i> Prev
                <% end %>
                 <%= link_to breast_cancer_path, class: "btn btn-primary" do %>
                    <i class="fa fa-chevron-right"></i> Next
                <% end %>
            </div>
            <%= link_to root_path, class: "btn btn-primary pull-left"  do %>
                <i class="fa fa-th-large"></i>
                <%= t("home")%>
            <% end %>
        </div>
        <!-- END Project Navigation -->

        <!-- Project Info -->
        <div class="row">
            <!-- Project Slider -->
            <div class="col-sm-5 site-block">
                <div id="project-carousel" class="carousel slide" data-ride="carousel" data-interval="3000">
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner text-center">
                        <div class="active item">
                            <%= image_tag "home/d1.jpg" %>
                        </div>
                        <div class="item">
                            <%= image_tag "home/d2.jpg" %>
                        </div>
                        <div class="item">
                            <%= image_tag "home/d3.jpg" %>
                        </div>
                    </div>
                    <!-- END Wrapper for slides -->

                    <!-- Controls -->
                    <a class="left carousel-control" href="#project-carousel" data-slide="prev">
                        <span>
                            <i class="fa fa-chevron-left"></i>
                        </span>
                    </a>
                    <a class="right carousel-control" href="#project-carousel" data-slide="next">
                        <span>
                            <i class="fa fa-chevron-right"></i>
                        </span>
                    </a>
                    <!-- END Controls -->
                </div>

                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td style="width: 50%;"><strong><%= t "home_infor.source" %></strong></td>
                            <td class="text-right"><%= @about.source %></td>
                        </tr>
                        <tr>
                            <td><strong><%= t "home_infor.category" %></strong></td>
                            <td class="text-right">Breast Cancer Wisconsin</td>
                        </tr>
                        <tr>
                            <td><strong>Website</strong></td>
                            <td class="text-right"><a href="javascript:void(0)"><%= @about.link %></a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- END Project Slider -->

            <!-- Project Details -->
            <div class="col-sm-7 site-block">
                <h3 class="site-heading"></strong><%= t("home_infor.data_set") %></h3>
                    <% if is_locale_en? %>
                    <%= @about.description.html_safe  if @about.description.present? %>
                   <% else %>
                    <%= @about.description_vi.html_safe if @about.description_vi.present? %>
                   <% end %>
             </div>
            <!-- END Project Details -->
        </div>
        <!-- END Project Info -->
        <hr>
    </div>
</section>
<!-- END Content -->

app/views/static_pages/home.html.erb
  <!-- Page Container -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!-- 'boxed' class for a boxed layout -->
        <div id="page-container">

            <!-- Home Carousel -->
            <div id="home-carousel" class="carousel carousel-home slide" data-ride="carousel" data-interval="5000">
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="active item">
                        <section class="site-section site-section-light site-section-top themed-background-default">
                            <div class="container">
                                <h1 class="text-center animation-slideDown hidden-xs"><strong></strong></h1>
                                <h2 class="text-center animation-slideUp push hidden-xs"></h2>
                                <p class="text-center animation-fadeIn">
                                    <%= image_tag "home/ca1.jpg"%>
                                </p>
                            </div>
                        </section>
                    </div>
                    <div class="item">
                        <section class="site-section site-section-light site-section-top themed-background-fire">
                            <div class="container">
                                <h1 class="text-center animation-fadeIn360 hidden-xs"><strong></strong></h1>
                                <h2 class="text-center animation-fadeIn360 push hidden-xs"></h2>
                                <p class="text-center animation-fadeInLeft">
                                    <%= image_tag "home/ca2.jpg" %>
                                </p>
                            </div>
                        </section>
                    </div>
                    <div class="item">
                        <section class="site-section site-section-light site-section-top themed-background-amethyst">
                            <div class="container">
                                <h1 class="text-center animation-hatch hidden-xs"><strong></strong></h1>
                                <h2 class="text-center animation-hatch push hidden-xs"></h2>
                                <p class="text-center animation-hatch">
                                    <%= image_tag "home/ca3.jpg" %>
                                </p>
                            </div>
                        </section>
                    </div>
                </div>
                <!-- END Wrapper for slides -->

                <!-- Controls -->
                <a id = "left-carousel" class="left carousel-control" href="#home-carousel" data-slide="prev">
                    <span>
                        <i class="fa fa-chevron-left"></i>
                    </span>
                </a>
                <a id = "right-carousel" class="right carousel-control" href="#home-carousel" data-slide="next">
                    <span>
                        <i class="fa fa-chevron-right"></i>
                    </span>
                </a>
                <!-- END Controls -->
            </div>
            <!-- END Home Carousel -->

            <!-- Action -->
            <section class="site-content site-section">
                <div class="container">
                    <div class="site-block text-center">
                        <% if !user_signed_in? %>
                            <%= link_to  new_user_session_path, class: "btn btn-lg btn-primary" do %>
                                <i class="fa fa-share"></i>
                                <%= t "signin" %>
                            <% end %>
                        <% end %>
                    </div>
                    <hr>
                </div>
            </section>
            <!-- END Action -->

            <!-- Promo #1 -->
            <section class="site-content site-section site-slide-content">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInRight" data-element-offset="-180">
                            <%= image_tag "home/t5.jpg", class: "img-responsive" %>
                        </div>
                        <div class="col-sm-6 col-md-5 col-md-offset-1 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInLeft" data-element-offset="-180">
                            <h3 class="h2 site-heading site-heading-promo"><strong><%= t("home_infor.quest_first") %></strong><%= t("home_infor.breast_cancer") %></h3>
                            <p class="promo-content">
                                <%= t "home_infor.summary1" %>
                                <%= link_to t("home_infor.learn_more"), breast_cancer_path %>
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </section>
            <!-- END Promo #1 -->

            <!-- Promo #2 -->
            <section class="site-content site-section site-slide-content">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-md-5 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInRight" data-element-offset="-180">
                            <h3 class="h2 site-heading site-heading-promo"><strong><%= t("home_infor.quest_first") %></strong><%= t("home_infor.data_mining") %></h3>
                            <p class="promo-content">
                                <%= t "home_infor.summary2" %>
                                <%= link_to t("home_infor.learn_more"), data_mining_path %>
                            </p>
                        </div>
                        <div class="col-sm-6 col-md-offset-1 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInLeft" data-element-offset="-180">
                            <%= image_tag "home/t3.jpg", class: "img-responsive" %>
                        </div>
                    </div>
                    <hr>
                </div>
            </section>
            <!-- END Promo #2 -->

            <!-- Testimonials -->
            <section class="site-content site-section">
                <div class="container">
                    <!-- Testimonials Carousel -->
                    <div id="testimonials-carousel" class="carousel slide carousel-html" data-ride="carousel" data-interval="4000">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#testimonials-carousel" data-slide-to="0" class="active"></li>
                            <li data-target="#testimonials-carousel" data-slide-to="1"></li>
                            <li data-target="#testimonials-carousel" data-slide-to="2"></li>
                        </ol>
                        <!-- END Indicators -->

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner text-center">
                            <div class="active item">
                                <p>
                                    <%= image_tag "home/a1.jpg", class: "img-circle"%>
                                </p>
                                <blockquote class="no-symbol">
                                    <p><%= t "home_infor.sen1" %></p>
                                    <footer><strong><%= t "home_infor.author1" %></strong>, <%= t "home_infor.title1" %></footer>
                                </blockquote>
                            </div>
                            <div class="item">
                                <p>
                                    <%= image_tag "home/a1.jpg", class: "img-circle"%>
                                </p>
                                <blockquote class="no-symbol">
                                    <p><%= t "home_infor.sen2" %></p>
                                    <footer><strong><%= t "home_infor.author1" %></strong>, <%= t "home_infor.title1" %></footer>
                                </blockquote>
                            </div>
                            <div class="item">
                                <p>
                                    <%= image_tag "home/a1.jpg", class: "img-circle"%>
                                </p>
                                <blockquote class="no-symbol">
                                    <p><%= t "home_infor.sen3" %></p>
                                    <footer><strong><%= t "home_infor.author1" %></strong>, <%= t "home_infor.title1" %></footer>
                                </blockquote>
                            </div>
                        </div>
                        <!-- END Wrapper for slides -->
                    </div>
                    <!-- END Testimonials Carousel -->
                </div>
            </section>
            <!-- END Testimonials -->

            <!-- Sign Up Action -->
            <section class="site-content site-section site-section-light themed-background-dark-night">
                <div class="container">
                    <div class="site-block text-center">
                        <form action="features.html" method="post" class="form-horizontal" onsubmit="return false;">
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <div class="input-group input-group-lg">
                                        <div class="input-group-btn">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
            <!-- END Sign Up Action -->
            <% if !user_signed_in? %>
                <section class="site-content site-section themed-background">
                    <div class="container">
                        <!-- Stats Row -->
                        <!-- CountTo (initialized in js/app.js), for more examples you can check out https://github.com/mhuggins/jquery-countTo -->
                        <div class="row" id="counters">
                            <div class="col-sm-4">
                                <div class="counter site-block">
                                    <span data-toggle="countTo" data-to= "1500000" data-after="+"></span>
                                    <small><%= t "home_infor.statistic1" %></small>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="counter site-block">
                                    <span data-toggle="countTo" data-to= "23" data-after="%"></span>
                                    <small><%= t "home_infor.statistic2" %></small>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="counter site-block">
                                    <span data-toggle="countTo" data-to= "50" data-after="%"></span>
                                    <small><%= t "home_infor.statistic3" %></small>
                                </div>
                            </div>
                        </div>
                        <!-- END Stats Row -->
                    </div>
                </section>
            <% end %>
        </div>
        <!-- END Page Container -->

        <!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
        <a href="#" id="to-top"><i class="fa fa-angle-up"></i></a>