config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi|ja/ do
    mount Ckeditor::Engine => '/ckeditor'
    root "static_pages#home"
    get  '/breast_cancer', to: "static_pages#breast_cancer"
    get  '/data_mining', to: "static_pages#data_mining"
    get  '/data_set', to: "static_pages#data_set"
    devise_for :users

    resources :users
    resources :diagnoses
    resources :groups do
      member do
        post :delete_member
      end
      member do
        post :add_member
      end
    end
    resources :test_algorithms
    resources :user_groups
    resources :fictions
    resources :abouts
    namespace :admin do
      root "users#index"
      resources :data_cancers
      resources :users
      resources :fictions
      resources :value_fictions
      resources :test_algorithms
      resources :diagnoses
      resources :groups
      resources :user_groups
      resources :rules
      resources :rule_id3s
      resources :abouts
      resources :knowledges do
        collection do
          get :create_knowledge
        end
      end
    end
  end
end

app/models/data_cancer.rb
class DataCancer < ApplicationRecord
  belongs_to :classification
  enum value: [1,2,3,4,5,6,7,8,9,10]
  ATTR_PARAMS = [
    :sample_code_number,
    :clump_thickness,
    :uniformity_of_cell_size,
    :uniformity_of_cell_shape,
    :marginal_adhesion,
    :single_epithelial_cell_size,
    :bare_nuclei,
    :bland_chromatin,
    :normal_nucleoli,
    :mitoses,
    :classification_id,
  ].freeze

  ATTR_PARAMS_DATA = [
    "clump_thickness",
    "uniformity_of_cell_size",
    "uniformity_of_cell_shape",
    "marginal_adhesion",
    "single_epithelial_cell_size",
    "bare_nuclei",
    "bland_chromatin",
    "normal_nucleoli",
    "mitoses"
  ].freeze

  delegate :name, to: :classification, prefix: true, allow_nil: true

  scope :get_training_data, -> do
    max_limit = (DataCancer.all.count * Settings.number_percent_training).round
    limit(max_limit)
  end

  scope :get_test_data, -> do
    max_limit = (DataCancer.all.count * Settings.number_percent_training).round
    offset(max_limit)
  end

  scope :is_clump_thickness, -> value do
    where clump_thickness: value
  end

  scope :is_uniformity_of_cell_size, -> value do
    where uniformity_of_cell_size: value
  end

  scope :is_uniformity_of_cell_shape, -> value do
    where uniformity_of_cell_shape: value
  end

  scope :is_marginal_adhesion, -> value do
    where marginal_adhesion: value
  end

  scope :is_single_epithelial_cell_size, -> value do
    where single_epithelial_cell_size: value
  end

  scope :is_bare_nuclei, -> value do
    where bare_nuclei: value
  end

  scope :is_bland_chromatin, -> value do
    where bland_chromatin: value
  end

  scope :is_normal_nucleoli, -> value do
    where normal_nucleoli: value
  end

  scope :is_mitoses, -> value do
    where mitoses: value
  end

  scope :is_classification, -> classification_id do
    where classification_id: classification_id
  end
end

app/controllers/admin/data_cancers_controller.rb
class Admin::DataCancersController < Admin::BaseController
  before_action :load_data_cancer, only: [:update, :edit, :show, :destroy]


  def index
    @search = DataCancer.ransack(params[:q])
    @data_cancers = @search.result
    @data_cancers = @data_cancers.page(params[:page]).per Settings.per_page.admin.data_cancer
     respond_to do |format|
      format.html
      format.js
     end
  end

  def new
    @data_cancer = DataCancer.new
  end

  def show
  end

  def create
    @data_cancer = DataCancer.new data_cancer_params
    if @data_cancer.save
      flash[:success] = t "admin.data_cancers.create_success"
      redirect_to admin_data_cancers_path
    else
      flash[:success] = t "admin.data_cancers.create_success"
      render :new
    end
  end

  def edit

  end

  def update
    if @data_cancer.update_attributes data_cancer_params
      flash[:success] = t "admin.data_cancers.updated_success"
      redirect_to [:admin, @data_cancer]
    else
      render :edit
    end
  end

  def destroy
    if @data_cancer.destroy
      flash[:success] = t("delete") + t("success")
      redirect_to admin_data_cancers_path
    else
      flash[:error] = t("delete") + t("fail")
      redirect_to admin_data_cancers_path
    end
  end

  private

  def load_data_cancer
    @data_cancer = DataCancer.find_by id: params[:id]
    return if @data_cancer.present?
    flash[:warning] = t "not_found_item"
    redirect_to :back
  end

  def data_cancer_params
    params.require(:data_cancer).permit DataCancer::ATTR_PARAMS
  end
end

app/helpers/admin/data_cancers_helper.rb
module Admin::DataCancersHelper
end

app/views/admin/data_cancers/_data_cancer.html.erb
<tr id="data-cancer-#{data_cancer.id}">
  <td>
    <%= current_index @data_cancers.current_page, Settings.per_page.admin.data_cancer, data_cancer_counter %>
  </td>
  <td><%= "A#{data_cancer.clump_thickness}" %></td>
  <td><%= "B#{data_cancer.uniformity_of_cell_size}"%></td>
  <td><%= "C#{data_cancer.uniformity_of_cell_shape}" %></td>
  <td><%= "D#{data_cancer.marginal_adhesion }"%></td>
  <td><%= "E#{data_cancer.single_epithelial_cell_size}" %></td>
  <td><%= "F#{data_cancer.bare_nuclei}" %></td>
  <td><%= "G#{data_cancer.bland_chromatin}" %></td>
  <td><%= "H#{data_cancer.normal_nucleoli}" %></td>
  <td><%= "I#{data_cancer.mitoses}" %></td>
  <td><%= t "diagnose.#{data_cancer.classification_name}" %></td>
  <td class="text-center">
      <div class="btn-group btn-group-xs">
        <%= link_to admin_data_cancer_path(data_cancer), class: "btn btn-default" do %>
          <i class="fa fa-eye"></i>
        <% end %>
        <%= link_to edit_admin_data_cancer_path(data_cancer), class: "btn btn-warning" do %>
          <i class="fa fa-pencil"></i>
        <% end %>
        <%= link_to admin_data_cancer_path(data_cancer),
          method: :delete, class: "btn btn-danger", data: {confirm: t("are_you_sure")} do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div>
    </td>
</tr>

app/views/admin/data_cancers/_edit_form_data_cancer.html.erb
<%= simple_form_for [:admin, @data_cancer] do |f| %>
<div class="col-md-6 col-sm-6 col-xs-6 personal-info">
  <div class="fix-clear form-group">
    <%= f.label :clump_thickness, t("clump_thickness"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :clump_thickness, get_fiction_by_name(Settings.fiction.clump_thickness).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:clump_thickness].each do |err|%>
        <li><span class="help-block"><%= t("clump_thickness") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :uniformity_of_cell_size, t("uniformity_of_cell_size"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :uniformity_of_cell_size, get_fiction_by_name(Settings.fiction.uniformity_of_cell_size).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:uniformity_of_cell_size].each do |err|%>
        <li><span class="help-block"><%= t("uniformity_of_cell_size") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :uniformity_of_cell_shape, t("uniformity_of_cell_shape"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :uniformity_of_cell_shape, get_fiction_by_name(Settings.fiction.uniformity_of_cell_shape).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:uniformity_of_cell_shape].each do |err|%>
        <li><span class="help-block"><%= t("uniformity_of_cell_shape") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :marginal_adhesion, t("marginal_adhesion"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :marginal_adhesion, get_fiction_by_name(Settings.fiction.marginal_adhesion).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:marginal_adhesion].each do |err|%>
        <li><span class="help-block"><%= t("marginal_adhesion") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :single_epithelial_cell_size, t("single_epithelial_cell_size"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :single_epithelial_cell_size, get_fiction_by_name(Settings.fiction.single_epithelial_cell_size).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:single_epithelial_cell_size].each do |err|%>
        <li><span class="help-block"><%= t("single_epithelial_cell_size") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="col-md-6 col-sm-6 col-xs-6 personal-info">
  <div class="fix-clear form-group">
    <%= f.label :bare_nuclei, t("bare_nuclei"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :bare_nuclei, get_fiction_by_name(Settings.fiction.bare_nuclei).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:bare_nuclei].each do |err|%>
        <li><span class="help-block"><%= t("bare_nuclei") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :bland_chromatin, t("band_romatin"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :bland_chromatin, get_fiction_by_name(Settings.fiction.bland_chromatin).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:bland_chromatin].each do |err|%>
        <li><span class="help-block"><%= t("band_romatin") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :normal_nucleoli, t("nomal_nucleoli"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :normal_nucleoli, get_fiction_by_name(Settings.fiction.normal_nucleoli).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:normal_nucleoli].each do |err|%>
        <li><span class="help-block"><%= t("nomal_nucleoli") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :mitoses, t("mitoses"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :mitoses, get_fiction_by_name(Settings.fiction.mitoses).collect {|value_fiction| [value_fiction.name, value_fiction.value]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:mitoses].each do |err|%>
        <li><span class="help-block"><%= t("mitoses") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="fix-clear form-group">
    <%= f.label :classification_id, t("classification"), class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <div class="input-group">
        <div class="input-group-addon">
          <i class="fa fa-star"></i>
        </div>
        <%= f.select :classification_id, Classification.all.collect {|classification| [t("diagnose.#{classification.name}"), classification.id]}, {}, {class: "form-control input-md"} %>
      </div>
      <ul class = "errors">
        <% @data_cancer.errors[:classification_id].each do |err|%>
        <li><span class="help-block"><%= t("classification") + " #{err}" %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="fix-clear form-group row">
  <div class="col-md-offset-4 col-md-4">
    <%= f.submit t("register_account"),
    class: "btn btn-primary col-md-12" %>
  </div>
</div>
<% end %>

app/views/admin/data_cancers/_search_form.html.erb
<%= search_form_for [:admin, @search], class: "search_form_data_cancer" do |f| %>
  <%= f.text_field :clump_thickness_or_uniformity_of_cell_size_or_uniformity_of_cell_shape_or_marginal_adhesion_or_single_epithelial_cell_size_or_bare_nuclei_or_bland_chromatin_or_normal_nucleoli_or_mitoses_cont,
    placeholder: t("search.name_or_employee_code_or_email"),
    class: "form-control search_text" %>
<% end %>

app/views/admin/data_cancers/_table_header.html.erb
<tr class = "active name-colum" >
    <th>STT</th>
    <th><%= sort_link @search, :clump_thickness, t("clump_thickness") %></th>
    <th><%= sort_link @search, :uniformity_of_cell_size, t("uniformity_of_cell_size") %></th>
    <th><%= sort_link @search, :uniformity_of_cell_shape, t("uniformity_of_cell_shape") %></th>
    <th><%= sort_link @search, :marginal_adhesion, t("marginal_adhesion") %></th>
    <th><%= sort_link @search, :single_epithelial_cell_size, t("single_epithelial_cell_size") %></th>
    <th><%= sort_link @search, :bare_nuclei, t("bare_nuclei") %></th>
    <th><%= sort_link @search, :bland_chromatin, t("bland_chromatin") %></th>
    <th><%= sort_link @search, :normal_nucleoli, t("normal_nucleoli") %></th>
    <th><%= sort_link @search, :mitoses, t("mitoses") %></th>
    <th><%= sort_link @search, :classification_id, t("result") %></th>
    <th><%= t("action")%></th>
</tr>

app/views/admin/data_cancers/edit.html.erb
<% provide :title, t("admin.data_cancers.update_data_cancer") %>
<div class = "row">
  <div class = "block-title">
  </div>
  <div class = "block-content-full">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= t"admin.data_cancers.update_data_cancer" %>
        </h3>
      </div>
      <div class="panel-body form-horizontal">
        <div class="row">
          <%= render "edit_form_data_cancer" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <% if current_user.admin?%>
    <%= link_to admin_data_cancers_path, class: "btn btn-default" do %>
    <i class="fa fa-chevron-left"></i> <%= t "list_data_cancer" %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/admin/data_cancers/index.html.erb
<% provide :title, t("admin.data_cancers.title") %>
<div class = "row">
  <div class = "block-content-full">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= t"admin.data_cancers.list_data_cancers" %>
        </h3>
      </div>
      <div class="panel-body">
        <% if current_user.admin? %>
        <div class="row manage_user">
          <div class="col-md-6">
            <div class="users_button_group">
              <%= link_to create_knowledge_admin_knowledges_path,
                class: "btn btn-md btn-success float_right create_rule" do %>
                <i class="gi gi-plus"></i> <%= t "admin.knowledges.create_knowledges" %>
              <% end %>
              <%= link_to admin_rules_path, method: :Post,
                class: "btn btn-md btn-success float_right create_rule" do %>
                <i class="gi gi-plus"></i> <%= t "admin.rules.create_rules_c45" %>
              <% end %>
              <%= link_to admin_rule_id3s_path, method: :Post,
                class: "btn btn-md btn-success float_right create_rule" do %>
                <i class="gi gi-plus"></i> <%= t "admin.rules.create_rules_id3" %>
              <% end %>
            </div>
          </div>
          <div class = "col-md-offset-5 col-md-1">
            <%= link_to new_admin_data_cancer_path, class: "btn btn-md btn-success float_right create_rule" do %>
              <i class="gi gi-plus"></i> <%= t "admin.data_cancers.create" %>
            <% end %>
          </div>
        </div>
        <% end %>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead class = "header-table-data-cancer">
              <%= render "table_header" %>
            </thead>
            <tbody class = "data-cancers-content">
              <% if @data_cancers.present? %>
                <%= render(@data_cancers) %>
              <% else %>
                <div class = "col-md-4 text-danger">
                  <i class="fa fa-fw fa-exclamation-triangle"></i>
                  <strong><%= t(".data_not_find") %></strong>
                </div>
              <% end %>
            </tbody>
          </table>
        </div>
        <center class = "paginate-items"><%= paginate @data_cancers %></center>
      </div>
    </div>
  </div>
</div>

app/views/admin/data_cancers/index.js.erb
$('.data-cancers-content').html('<%= j render @data_cancers %>');
$('.paginate-items').html('<%= j paginate @data_cancers %>');
$('.header-table-data-cancer').html('<%= j render "table_header" %>');

app/views/admin/data_cancers/new.html.erb
<% provide :title, t("admin.data_cancers.create") %>
<div class = "row">
  <div class = "block-title">
  </div>
  <div class = "block-content-full">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= t"admin.data_cancers.create" %>
        </h3>
      </div>
      <div class="panel-body form-horizontal">
        <div class="row">
          <%= render "edit_form_data_cancer" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <% if current_user.admin?%>
    <%= link_to admin_data_cancers_path, class: "btn btn-default" do %>
    <i class="fa fa-chevron-left"></i> <%= t "list_data_cancer" %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/admin/data_cancers/show.html.erb
<% provide :title, t("admin.users.information_user") %>
<div class = "row">
  <div class = "block-title">
  </div>
  <div class = "block-content-full">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= t"admin.data_cancers.information_data_cancer" %>
        </h3>
      </div>
      <div class="panel-body">
        <table class="table table-hover">
          <tbody>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("clump_thickness") %>
                </strong>
              </td>
              <td><%= "A#{@data_cancer.clump_thickness}" %></td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("uniformity_of_cell_size") %>
                </strong>
              </td>
              <td><%= "B#{@data_cancer.uniformity_of_cell_size}"%></td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("uniformity_of_cell_shape") %>
                </strong>
              </td>
              <td><%= "C#{@data_cancer.uniformity_of_cell_shape}" %></td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("marginal_adhesion") %>
                </strong>
              </td>
              <td>
                <%= "D#{@data_cancer.marginal_adhesion }"%>
              </td>
            </tr>

            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%=  t("single_epithelial_cell_size") %>
                </strong>
              </td>
              <td>
                <%= "E#{@data_cancer.single_epithelial_cell_size}" %>
              </td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("bare_nuclei") %>
                </strong>
              </td>
              <td>
                <%= "F#{@data_cancer.bare_nuclei}" %>
              </td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("bland_chromatin") %>
                </strong>
              </td>
              <td>
                <%= "G#{@data_cancer.bland_chromatin}" %>
              </td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("normal_nucleoli") %>
                </strong>
              </td>
              <td>
                <%= "H#{@data_cancer.normal_nucleoli}" %>
              </td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("mitoses") %>
                </strong>
              </td>
              <td>
                <%= "I#{@data_cancer.mitoses}" %>
              </td>
            </tr>
            <tr>
              <td>
                <strong>
                  <i class="fa fa-star"></i> <%= t("result") %>
                </strong>
              </td>
              <td>
                <%= t "diagnose.#{@data_cancer.classification_name}" %>
              </td>
            </tr>
          </tbody>
        </table>
        <% if current_user.admin? %>
          <%= link_to t("admin.data_cancers.update_data_cancer"), edit_admin_data_cancer_path,
            class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <% if current_user.admin?%>
          <%= link_to admin_data_cancers_path, class: "btn btn-default" do %>
            <i class="fa fa-chevron-left"></i> <%= t "list_data_cancer" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>