config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi|ja/ do
    mount Ckeditor::Engine => '/ckeditor'
    root "static_pages#home"
    get  '/breast_cancer', to: "static_pages#breast_cancer"
    get  '/data_mining', to: "static_pages#data_mining"
    get  '/data_set', to: "static_pages#data_set"
    devise_for :users

    resources :users
    resources :diagnoses
    resources :groups do
      member do
        post :delete_member
      end
      member do
        post :add_member
      end
    end
    resources :test_algorithms
    resources :user_groups
    resources :fictions
    resources :abouts
    namespace :admin do
      root "users#index"
      resources :data_cancers
      resources :users
      resources :fictions
      resources :value_fictions
      resources :test_algorithms
      resources :diagnoses
      resources :groups
      resources :user_groups
      resources :rules
      resources :rule_id3s
      resources :abouts
      resources :knowledges do
        collection do
          get :create_knowledge
        end
      end
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :image, GroupImageUploader

  belongs_to :owner, class_name: User.name, foreign_key: :user_id

  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups

  validates :name, presence: true
  validates :user_id, presence: true

  scope :recent, ->{order created_at: :desc}

  def add_list_user_group user_groups
    user_groups.each do |user_group|
      user_group.save
    end
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :new_group, only: :index
  before_action :load_group, only: [:show, :edit, :destroy, :update]
  before_action :load_user_groups, only: [:show, :edit]
  before_action :load_users, only: [:show]

  def index
    @search = Group.ransack(params[:q])
    @groups = @search.result
    @groups = @groups.page(params[:page]).per Settings.per_page.admin.group
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @group = Group.new group_params
    if @group.save
      flash[:success] = t "admin.groups.create_group_success"
    else
      flash[:error] = t "admin.groups.create_group_fail"
    end
    redirect_to groups_path
  end

  def show
  end

  def update
    if @group.update_attributes group_params
      flash[:success] = t "admin.groups.update_group_success"
    else
      flash[:error] = t "admin.groups.update_group_fail"
    end
    redirect_to groups_path
  end

  def destroy
    if @group.destroy
      flash[:success] =  t "admin.groups.delete_group_success"
    else
      flash[:error] = t "admin.groups.delete_group_fail"
    end
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit :name, :user_id, :image, :description
  end

  def load_group
    @group = Group.find_by id: params[:id]
    return if @group
    flash[:error] = t "not_found_item"
    redirect_to :back
  end

  def load_user_groups
    @user_groups = @group.user_groups
  end

  def load_users
    @users= @group.users
  end

  def new_group
    @group = Group.new
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :new_group, only: :index
  before_action :load_group, only: [:show, :edit, :destroy, :update, :add_member, :delete_member]
  before_action :is_owner

  def index
    @title = t "groups.list_groups"
    @search = current_user.admin? ? Group.ransack(params[:q]) : current_user.groups.ransack(params[:q])
    @groups = @search.result
    @groups = @groups.page(params[:page]).per Settings.per_page.admin.group
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @title = t "groups.information_group"
    user_ids = @group.users.is_normal_user.search_by(params[:search]).pluck(:id)
    @users_inside = @group.user_groups.of_user_ids(user_ids).includes(:user)
    init_variables
    respond_to do |format|
      format.html
      format.js
    end
  end

  def add_member
    assign_user params[:user_groups][:user_ids], @group
    redirect_to :back
  end

  def delete_member
    @user_ids = params[:user_ids].strip.split(",").map(&:to_i)
    unassign_user @user_ids, @group
    redirect_to :back
  end

  private

  def assign_user user_ids, group
    assign_user = AssignUserService.new
    .create user_ids, group, t("user_groups.create_not_successfully")
    message_notice t("user_groups.create_successfully"), assign_user
  end

  def unassign_user user_ids, group
    unassign_user = AssignUserService.new
    .destroy user_ids, group, t("user_groups.delete_not_successfully")
    message_notice t("user_groups.delete_successfully"), unassign_user
  end

  def group_params
    params.require(:group).permit :name, :user_id, :image, :description
  end

  def load_group
    @group = Group.find_by id: params[:id]
    return if @group
    flash[:error] = t "not_found_item"
    redirect_to :back
  end

  def new_group
    @group = Group.new
  end

  def message_notice message_success, type
    return flash[:error] = type[:error] unless type[:success]
    flash[:success] = message_success
  end

  def init_variables
    @user_group = UserGroup.new
    @users_outside = User.not_in_group.is_normal_user.includes(:groups)
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_assign_user.html.erb
<div id="add-users-into-group" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header modal-search-content">
        <button type="button" class="close" data-dismiss="modal">&times;
        </button>
        <h4 class="modal-title"><%= t "admin.groups.list_user" %></h4>

        <div class="col-md-12">
          <div class="input-group c-search">
            <input type="text" class="form-control"
              id="assign-list-user-group-search">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <span class="gi gi-search text-muted"></span>
              </button>
            </span>
          </div>
        </div>
      </div>

      <%= form_for :group, url: add_member_group_path(@group) do |f| %>
        <div class="modal-body user-group-modal-body">
          <ul class="list-group" id="assign-list-user">
            <%= render "collection_check_boxes", users: @users_outside %>
          </ul>
        </div>
        <div class="modal-footer">
          <%= f.submit t("user_groups.add_member"),
            class: "btn btn-primary btn-add-member-into-group" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_collection_check_boxes.html.erb
<input type="checkbox" id="select-all-user-outside">
<%= t "admin.groups.select_all" %>
<div id="check-box-all-checked">
  <%= collection_check_boxes :user_groups, :user_ids, users, :id, :name do |f| %>
    <li class="list-group-item hide-user-group-search">
      <div class="col-xs-12 col-sm-8">
        <div class="checkbox col-md-8 checkbox-user-group search-checkbox">
          <%= f.label {f.check_box + f.text}%>
        </div>
        <div class="col-xs-12 col-md-4">
          <%= image_tag f.object.avatar.url, class: "img-scale img-circle avatar-user-group" %>
        </div>
      </div>
      <div class="col-sm-4">
        <% f.object.user_groups.each do |user_group| %>
          <label class="label-info label-custom"><%= user_group.group_name %></label>
        <% end %>
      </div>
      <div class="clearfix"></div>
    </li>
  <% end %>
</div>

app/views/groups/_form.html.erb
<%= simple_form_for [:admin, @group], multipart: true do |f| %>
  <div class="form-group">
    <%= f.label :name, t("admin.groups.name"), class: "field-compulsory-before" %>
    <div>
      <%= f.text_field :name, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :user_id, t("admin.groups.owner"), class: "field-compulsory-before" %>
    <div>
      <%= f.select :user_id, User.is_not_normal_user.collect { |user| [user.name, user.id] }, {}, {class: "form-control col-md-9"}%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, t("admin.groups.image") %>
    <%= f.file_field :image, accept: Settings.image_format_accept, class: "" %>
  </div>

  <div class="form-group">
    <%= f.label :description, t("admin.groups.description"), class: "field-compulsory-before" %>
    <div>
      <%= f.text_area :description, class: "form-control ckeditor" %>
    </div>
  </div>

  <div class = "form-group">
    <div class="text-center row">
      <%= f.button :submit, t("submit"), class: "col-md-offset-2 col-md-8 btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="col-xs-3 col-sm-6 col-md-4 col-md-4">
  <div class="thumbnail product">
    <div class="caption">
      <% if current_user.is_owner_of_group?(group) %>
        <%= link_to group, class: "widget widget-hover-effect3" do %>
          <div class="img-caption text-center">
            <%= image_tag group.image_url, class: "image-group" %>
          </div>
        <% end %>
      <% else %>
        <div class="img-caption text-center">
          <%= image_tag group.image_url, class: "image-group" %>
        </div>
      <% end %>

      <h5>
        <%= t ".name" %>:
        <strong class="text-info"><%= group.name %></strong>
      </h5>

      <div class="btn-group btn-group-xs">
        <% if current_user.is_owner_of_group?(group) %>
          <button type="button" class="btn btn-success" data-toggle="modal" data-target=<%= "#"+ "group-" + "#{group.id}" %>>
            <i class="gi gi-pencil"></i> <%= t "admin.groups.update_group" %>
          </button>
          <%= link_to group, class: "btn btn-info" do %>
            <i class="fa fa-cog"></i>
            <span><%= t "admin.groups.list_members" %></span>
          <% end %>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to [:admin, group],
            method: :delete, class: "btn btn-danger", data: {confirm: t("are_you_sure")} do %>
            <i class="fa fa-trash"></i>
            <span><%= t "admin.groups.delete" %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id=<%= "group-" + "#{group.id}" %> class="modal fade" role="dialog">
  <div class="modal-dialog  modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t "admin.groups.update_group" %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [:admin, group], multipart: true do |f| %>
          <div class="form-group">
            <%= f.label :name, t("admin.groups.name"), class: "field-compulsory-before" %>
            <div>
              <%= f.text_field :name, required: true, class: "form-control" %>
            </div>
          </div>
          <% if current_user.admin? %>
            <div class="form-group">
              <%= f.label :user_id, t("admin.groups.owner"), class: "field-compulsory-before" %>
              <div>
                <%= f.select :user_id, get_owners.collect { |user| [user.name, user.id] }, {}, {class: "form-control col-md-9"}%>
              </div>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.label :image, t("admin.groups.image") %>
            <div class="text-center col-md-12">
              <%= image_tag group.image.url, class: "height-250 image-register", id: "img_prev" %>
              <%= f.file_field :image, accept: Settings.image_format_accept, class: "avatar-register" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :description, t("admin.groups.description"), class: "field-compulsory-before" %>
            <div>
              <%= f.text_area :description, class: "form-control ckeditor" %>
            </div>
          </div>

          <div class = "form-group">
            <div class="text-center row">
              <%= f.button :submit, t("submit"), class: "col-md-offset-2 col-md-8 btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/groups/_list_member.html.erb
<tr>
  <td class="width-5-percent">
    <% if current_user.is_owner_of_group? @group %>
      <%= check_box_tag user_group.user_id, user_group.user_id, false,
        class: "member-group" %>
    <% end %>
  </td>
  <td class="width-10-percent">
    <%= image_tag user_group.user_avatar.url, class: "img-scale img-circle avatar-member-group" %>
  </td>
  <td class="width-35-percent"><%= link_to user_group.user_name, user_group.user %></td>
  <td class="width-20-percent"><%= user_group.user_patient_code %></td>
  <td class="width-20-percent"><%= user_group.user_gender %></td>
</tr>

app/views/groups/_search_form.html.erb
<%= search_form_for @search, class: "search_form_group" do |f| %>
  <%= f.text_field :name_cont,
    placeholder: t("search.name_or_employee_code_or_email"),
    class: "form-control search_text" %>
<% end %>

app/views/groups/_table_member.html.erb
<div class="table-responsive">
  <table id="general-table" class="table fixed_headers">
    <thead class = "active">
      <tr>
        <td></td>
        <td><%= t "admin.users.avatar" %></td>
        <td><%= t "admin.users.name" %></td>
        <td><%= t "admin.users.patient_code" %></td>
        <td><%= t "admin.users.gender" %></td>
      </tr>
    </thead>
  <tbody id = "group-members-content">
    <%= render partial: "list_member", collection: @users_inside,
      as: :user_group %>
  </tbody>
</table>
</div>

app/views/groups/index.html.erb
<% provide :title, t("admin.groups.title") %>
<div class = "row">
  <div class = "block-content-full">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
         <%= t "admin.groups.list_groups" %>
       </h3>
     </div>
     <div class="panel-body">
      <div class="row manage_user">
        <% if current_user.admin? %>
          <div class="col-md-4">
            <div class="users_button_group">
              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
                <i class="gi gi-plus"></i> <%= t "admin.groups.create_group" %>
              </button>
            </div>
          </div>
          <div class="col-md-offset-4 col-md-4">
            <%= render "search_form" %>
          </div>
        <% elsif current_user.owner? %>
          <div class="col-md-offset-8 col-md-4">
            <%= render "search_form" %>
          </div>
        <% end %>
      </div>
      <div class="row">
        <div id="groups-content">
          <% if @groups.present? %>
            <%= render(@groups) %>
          <% else %>
            <div class = "col-md-4 text-danger">
              <i class="fa fa-fw fa-exclamation-triangle"></i>
              <strong><%= t(".data_not_find") %></strong>
            </div>
          <% end %>
        </div>
      </div>
      <center class = "paginate-items"><%= paginate @groups %></center>
    </div>
  </div>
</div>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog  modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= t "admin.groups.create_group" %></h4>
      </div>
      <div class="modal-body">
          <%= render "form" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/groups/index.js.erb
$('#groups-content').html('<%= j render @groups %>');
$('.paginate-items').html('<%= j paginate @groups %>');

app/views/groups/show.html.erb
<div class="toppad col-md-12" id="group-body">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title text-center">
        <%= t "admin.groups.information_group" %>
      </h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-offset-1 col-md-3">
          <%= image_tag @group.image.url,  class: "image-register" %>
        </div>
        <div class="col-md-8 row">
          <table class="table">
            <tbody>
              <tr>
                <td class="col-md-3"><%= t "admin.groups.name" %></td>
                <td><span><%= @group.name %></span></td>
              </tr>
              <tr>
                <td class="col-md-3"><%= t "admin.groups.owner" %></td>
                <td><span><%= @group.owner.name %></span></td>
              </tr>
              <tr>
                <td><%= t "admin.groups.description" %></td>
                <td><span><%= @group.description.html_safe if @group.description.present? %></span></td>
              </tr>
              <tr>
                <td><%= t "admin.groups.number_member" %></td>
                <td><span id="count"><%= @group.users.count %></span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title text-center">
        <%= t "admin.groups.list_members" %>
      </h3>
    </div>
    <div class="row">
      <br>
      <div class="col-md-12 row">
        <% if current_user.is_owner_of_group? @group %>
          <div class="col-md-offset-1 col-md-2">
            <input type="checkbox" id="select-all-user-inside" class="col-md-1"
              value="">
            <span class="col-md-9">
              <%= t "admin.groups.select_all" %>
            </span>
          </div>
        <% end %>
        <div class="col-md-5 pull-right">
          <%= form_tag @group, remote: true, method: :get,
              id: "group_members_search" do %>
            <div class="form-group col-md-10">
              <%= text_field_tag :search, params[:search],
                class: "form-control", placeholder: t("user_groups.search") %>
            </div>
          <% end %>
        </div>
        <div class = "col-md-2">
          <%= link_to new_diagnosis_path, class: "btn btn-sm btn-success" do %>
            <i class="gi gi-plus"></i> <%= t "admin.diagnoses.create_diagnose" %>
          <% end %>
        </div>
        <% if current_user.is_owner_of_group? @group %>
          <div class="col-md-1">
            <button type="button" class="btn btn-primary col-md-12 btn-sm"
                data-toggle="modal" data-target="#add-users-into-group">
                <%= t "user_groups.add_member" %>
            </button>
          </div>
          <div class="col-md-1">
            <%= form_for :group, url: delete_member_group_path(@group) do |f| %>
              <%=  hidden_field_tag :user_ids %>
              <%=  hidden_field_tag :user_ids_tmp %>
              <% if current_user.is_owner_of_group? @group %>
                <%= f.submit t("user_groups.remove_member"),
                  id: "btn-delete-user-into-group",
                  class: "btn btn-danger btn-sm" %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-12">
            <div class="row overflow-list-user" id="list-users-group">
              <%= render "table_member" %>
            </div>
        </div>
      </div>
    </div>
      <%= render "assign_user" %>
  </div>
</div>
<div class="loader hide hide-load-modal"></div>

app/views/groups/show.js.erb
$('#group-members-content').html('<%= j render partial: "list_member", collection: @users_inside,
      as: :user_group %>');